"""Keep an OpenSSH `allowed_signers` file in step with the trust store.

Why this exists. `beamsig verify` reads the trust store directly, so it picks
up a newly discovered CA immediately. `git log` does not: git shells out to
stock `ssh-keygen -Y find-principals` against `gpg.ssh.allowedSignersFile`,
which is a flat file that knows nothing about our store. So a commit from
another Beams tenant verified under `beamsig verify-commit` while `git log`
still reported `%G?` = `U`, and a re-run never fixed it because nothing
updated that file. Observed on a real commit from `quiet-hat.beams.sh`.

So whenever a CA is pinned or discovered, regenerate the file from the store.

Regenerate rather than append: it is idempotent, cannot accumulate duplicates,
and drops anchors that have been removed.

Note what `allowed_signers` cannot express: there is no field for the cluster a
`cert-authority` line belongs to. With several tenants listed, stock
`ssh-keygen` cannot tell them apart -- any trusted tenant's beam verifies as
any other's. `beamsig verify` does distinguish them, because it keys trust by
cluster. That asymmetry is unavoidable here and is why the cluster name is
written into the comment field, where a human can at least see it.
"""
import os

from .verify import load_trust_anchors

# Written into every line we generate, so we can recognise our own output and
# refuse to clobber a file somebody maintains by hand.
MARKER = "teleport-user-ca"

DEFAULT_PRINCIPAL = os.environ.get("BEAMSIG_PRINCIPAL", "beams")


def default_path(config_dir=None) -> str:
    cfg = config_dir or os.environ.get(
        "BEAMSIG_CONFIG_DIR", os.path.expanduser("~/.config/beamsig"))
    return os.path.join(cfg, "allowed_signers")


def generate(sources, principal: str = None) -> str:
    principal = principal or DEFAULT_PRINCIPAL
    seen = set()
    lines = [
        "# Generated by beamsig. Regenerated whenever a CA is pinned or",
        "# discovered; edits will be lost. allowed_signers has no way to say",
        "# which cluster a CA belongs to, so stock ssh-keygen cannot tell the",
        "# clusters below apart -- use `beamsig verify` for that.",
    ]
    for anchor in load_trust_anchors(sources, allow_empty=True):
        import base64
        from .wire import Reader
        keytype = Reader(anchor.blob).string().decode()
        b64 = base64.b64encode(anchor.blob).decode()
        if b64 in seen:
            continue
        seen.add(b64)
        cluster = anchor.cluster or "unlabelled"
        lines.append(f"{principal} cert-authority {keytype} {b64} "
                     f"{MARKER} {cluster}")
    return "\n".join(lines) + "\n"


def safe_to_write(path: str) -> bool:
    """True if the file is absent, empty, or previously generated by us."""
    if not os.path.exists(path):
        return True
    try:
        with open(path) as f:
            content = f.read()
    except OSError:
        return False
    if not content.strip():
        return True
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if MARKER not in line:
            return False        # somebody's own entry; leave the file alone
    return True


def sync(dest: str = None, sources=None, principal: str = None) -> int:
    """Rewrite `dest` from `sources`. Returns the number of CAs written, or -1
    if the file was left alone because it is not ours."""
    dest = dest or default_path()
    if sources is None:
        from . import discover as disc
        sources = [d for d in (disc.default_store(), disc.cache_dir())
                   if os.path.isdir(d)]
    if not safe_to_write(dest):
        return -1
    text = generate(sources, principal)
    n = sum(1 for line in text.splitlines()
            if line and not line.startswith("#"))
    os.makedirs(os.path.dirname(dest) or ".", mode=0o700, exist_ok=True)
    tmp = dest + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, dest)
    return n
